### ISSUE TITLE
Difference between RAW and parsed

### ISSUE THREAD

**Issue by cannod** [Iezious/rcjoy#17]
Hi,

Firstly thanks for sharing your project up on Github. I have finished building and am testing it out using a Logitech 3D extreme joystick. I'm having some problems with the joystick configuration and am trying to work out what is going on.

If I enable Live update and I have RAW selected for the joystick I can see the correct buttons being pressed and elevator, rudder etc look good. If I selected Parsed then the live update shows all sorts of weird things such as different buttons being pressed and when you move the joystick some of the buttons flicker from on to off. 

If you use the touch screen and select the joystick, It looks like the parsed data is being shown. Showing the same erratic behaviour as the parsed live update data. 

So what is the difference between RAW and Parsed data for the joystick?

Thanks

Dave

**Comment by Iezious** [comment]
Test it, plz, using this: https://drive.google.com/open?id=0B7qKXhcdAsFpcVItdFZwSDVTZXc
