### ISSUE TITLE
PPM channel options

### ISSUE THREAD

**Issue by geekness** [Iezious/rcjoy#4]
Is there an option to choose how many channels? I would need somewhere around 12.

Choosing whether its negative or positive.

And choosing the time between each channel, and/or the full frame length.

**Comment by geekness** [comment]
I see there is option to change those settings manually in "PPMGenerator.c", but perhaps is there thoughts to have options in software?

**Comment by Iezious** [comment]
Channels number (up to 16), PPM min and max values are set in model edit dialog. 
PPM frame length is 2500*Channel number
