### ISSUE TITLE
Can the hardware operate without a touch screen?

### ISSUE THREAD

**Issue by geekness** [Iezious/rcjoy#5]
I know you can choose to have the touch screen on or off, but if I want to bury the board inside of my controller, can I use it without the screen?

**Comment by Iezious** [comment]
No, model selection is done in screen menu.

**Comment by geekness** [comment]
Is there any way at all to have model selection done through Windows GUI?

**Comment by failMode** [comment]
If you only have one model setup through the GUI it will automatically be used. I have only one model\config set up and never have to use the screen in general operation. i.e. power the board (along with the transmitter module), plug in the joystick and go.
