### ISSUE TITLE
General question on the GUI

### ISSUE THREAD

**Issue by geekness** [Iezious/rcjoy#6]
What program did you use to create the windows GUI for this project?
Im thinking about creating something similar for the Teensy 3.2 board.
I'll just have a bunch inputs and a single PPM output, but I want to be able to make and select different models in a windows GUI similar to what you have.

Any help/advice you can offer will be greatly appreciated.

**Comment by Iezious** [comment]
I'm using Visual Studio + VisualGDB, currently 2015
